Adding a feedback form in k8s doc
fermyon/developer pull request #1050
Opened 2023-11-17 21:43 UTC by macolso

Content must go through a pre-merge checklist.

## Pre-Merge Content Checklist

This documentation has been checked to ensure that:

- [ ] The `title, `template`, and `date` are all set
- [ ] Does this PR have a new menu item (anywhere in `templates/*.hbs` files) that points to a document `.md` that is set to publish in the future? If so please only publish the `.md` and `.hbs` changes in real-time (otherwise there will be a menu item pointing to a `.md` file that does not exist)
- [ ] File does not use CRLF, but uses plain LF (hint: use `cat -ve <filename> | grep '^M' | wc -l` and expect 0 as a result) 
- [ ] Has passed [`bart check`](https://developer.fermyon.com/bartholomew/quickstart)
- [ ] Has been manually tested by running in Spin/Bartholomew (hint: use `PREVIEW_MODE=1` and run `npm run styles` to update styling)
- [ ] Headings are using Title Case
- [ ] Code blocks have the programming language set to properly highlight syntax and the proper copy directive
- [ ] Have tested with `npm run test` and resolved all errors
- [ ] Relates to an existing (potentially outdated) blog article? If so please add URL in blog to point to this content.

2023-11-17 21:45 UTC, karthik2804 approved these changes

2023-11-19 18:33 UTC, itowlson requested changes
I'm very sorry but there was a _second_ typo which I missed when looking at it before

2023-11-19 18:33 UTC, itowlson commented on content/spin/v1/kubernetes.md
> +> Fermyon wants to know how we can build you the best Spin experience on Kuberenetes. Let us know what you need to efficiently run Spin applications at scale on Kubernetes with this [short survey](ht
```suggestion
> Fermyon wants to know how we can build you the best Spin experience on Kubernetes. Let us know what you need to efficiently run Spin applications at scale on Kubernetes with this [short survey](https://fibsu0jcu2g.typeform.com/to/H8G8Nzgs?utm_campaign=thanks&utm_source=hs_email&utm_medium=email&_hsenc=p2ANqtz-_IwqD36cFYu9skvZBobOVZjjdXtGO3Z126WweaeKBWZz8wM4G_LZG7L0esIOS4tcASX8LM).  
```

2023-11-20 01:24 UTC, itowlson approved these changes

2023-11-20 01:53 UTC, tpmccallum approved these changes
Kubernetes misspelled on the `v2` page—otherwise LGTM.

2023-11-20 01:53 UTC, tpmccallum commented on content/spin/v2/kubernetes.md
> +> Fermyon wants to know how we can build you the best Spin experience on Kuberenetes. Let us know what you need to efficiently run Spin applications at scale on Kubernetes with this [short survey](ht
```suggestion
> Fermyon wants to know how we can build you the best Spin experience on Kubernetes. Let us know what you need to efficiently run Spin applications at scale on Kubernetes with this [short survey](https://fibsu0jcu2g.typeform.com/to/H8G8Nzgs?utm_campaign=thanks&utm_source=hs_email&utm_medium=email&_hsenc=p2ANqtz-_IwqD36cFYu9skvZBobOVZjjdXtGO3Z126WweaeKBWZz8wM4G_LZG7L0esIOS4tcASX8LM).  
```

2023-11-20 15:54 UTC, merged