Spin-O-Llama sample added
fermyon/developer pull request #1089
Opened 2023-12-12 22:39 UTC by BLaZeKiLL

Content must go through a pre-merge checklist.

## Pre-Merge Content Checklist

This documentation has been checked to ensure that:

- [x] The `title, `template`, and `date` are all set
- [] Does this PR have a new menu item (anywhere in `templates/*.hbs` files) that points to a document `.md` that is set to publish in the future? If so please only publish the `.md` and `.hbs` changes in real-time (otherwise there will be a menu item pointing to a `.md` file that does not exist)
- [x] File does not use CRLF, but uses plain LF (hint: use `cat -ve <filename> | grep '^M' | wc -l` and expect 0 as a result) 
- [ ] Has passed [`bart check`](https://developer.fermyon.com/bartholomew/quickstart)
- [ ] Has been manually tested by running in Spin/Bartholomew (hint: use `PREVIEW_MODE=1` and run `npm run styles` to update styling)
- [ ] Headings are using Title Case
- [ ] Code blocks have the programming language set to properly highlight syntax and the proper copy directive
- [ ] Have tested with `npm run test` and resolved all errors
- [ ] Relates to an existing (potentially outdated) blog article? If so please add URL in blog to point to this content.

2023-12-13 00:09 UTC, tpmccallum commented
Thanks @BLaZeKiLL 
I just need to check a quick thing before approving and merging.
@karthik2804 do you know why this sample would be showing up 3 times in the preview of the PR?
![Screenshot 2023-12-13 at 10 07 56](https://github.com/fermyon/developer/assets/9831342/0f3e5c42-46ab-4847-bb79-2899bbaf99ee)

2023-12-13 00:32 UTC, tpmccallum requested changes

2023-12-13 00:32 UTC, tpmccallum commented on content/api/hub/sample_ollama.md
> +title = "Rust HTTP trigger template"
```suggestion
title = "OLlama using Spin"
```
Can we please use this new name, to prevent clashes with existing items in the hub?
Thanks so much.

2023-12-13 00:33 UTC, tpmccallum commented on content/api/hub/sample_ollama.md
> +title = "Rust HTTP trigger template"
Renders correctly if using unique name:
![Screenshot 2023-12-13 at 10 32 51](https://github.com/fermyon/developer/assets/9831342/7f9c6595-cbb0-4041-a0cd-01ec21189922)

2023-12-13 00:36 UTC, itowlson commented
@BLaZeKiLL also, could you sign your commit please?  We need all commits to be signed-off and GPG signed.  Thanks!

2023-12-13 16:21 UTC, BLaZeKiLL commented
I'll go over the feedback, I still have some content to add but gotta catch a flight.

2023-12-15 15:47 UTC, BLaZeKiLL commented
I'll make a different pull request. and make sure commits are signed from the beginning

2023-12-15 15:47 UTC, closed without merging