Updating the hub_api for hub CLI
fermyon/developer pull request #1373
Opened 2024-08-29 18:41 UTC by VamshiReddy02

ref: [#3 ](https://github.com/itowlson/spin-hub-cli/pull/3)
In this PR, I added `template_id `and `repo_url` to the `hub_list_api`, which are very important for the Hub CLI.

2024-08-29 20:10 UTC, itowlson requested changes
Looks good, just one place where some fields got left blank.

I also noticed that the Jekyll template (https://developer.fermyon.com/hub/preview/template_jekyll) didn't score an API entry.  Is this intentional?

2024-08-29 20:10 UTC, itowlson commented on content/api/hub/template_sqlite_explorer.md
> +template_id = ""
```suggestion
template_id = "spin-sqlite-explorer"
```

2024-08-29 20:10 UTC, itowlson commented on content/api/hub/template_sqlite_explorer.md
> +repo_url = ""
```suggestion
repo_url = "https://github.com/karthik2804/spin-sqlite-web-cli"
```

2024-08-29 22:21 UTC, VamshiReddy02 commented
oopsie! I missed some templates, my bad.

2024-08-29 22:32 UTC, itowlson approved these changes
Looks good!  Thanks for this - I'm excited to see this being built out!

2024-08-29 22:34 UTC, itowlson commented
I'm going to hold off merging so Karthik has the chance to take a look, since he built the original API machinery and is more familiar with it than I am.

2024-08-30 08:01 UTC, karthik2804 approved these changes

2024-08-30 21:27 UTC, merged