Added a message to search when no items match
fermyon/developer pull request #1413
Opened 2024-11-05 17:21 UTC by VamshiReddy02

Fixes: #1374
Link: https://fermyon-developer-jvfddbpo.fermyon.app/hub

2024-11-07 02:01 UTC, itowlson requested changes
This looks great - the message makes this situation much clearer.  Unfortunately, there seems to be some odd formatting glitch with close braces,  Other than that it looks good to go!  Sorry for being picky

2024-11-07 02:01 UTC, itowlson commented on spin-up-hub/src/components/ContentListing.vue
> + } else {
I'm guessing this is either a rogue auto-formatter or a GitHub display glitch, but every line that starts with a `}` seems to have gotten clamped to the left edge.  Could you sanity-check the formatting throughout please?

2024-11-10 18:35 UTC, itowlson approved these changes
LGTM - thanks for fixing that nit @VamshiReddy02!

2024-11-11 09:48 UTC, karthik2804 approved these changes

2024-11-13 12:56 UTC, merged