Update CLI reference
fermyon/developer pull request #263
Opened 2023-01-31 06:03 UTC by tpmccallum

Signed-off-by: tpmccallum tim.mccallum@fermyon.com

This is in relation to issue https://github.com/fermyon/developer/issues/262

Content must go through a pre-merge checklist.

## Pre-Merge Content Checklist

This documentation has been checked to ensure that:

- [x] The `title, `template`, and `date` are all set
- [x] File does not use CRLF, but uses plain LF (hint: use `cat -ve <filename> | grep '^M' | wc -l` and expect 0 as a result) 
- [ ] Has passed [`bart check`](https://bartholomew.fermyon.dev/quickstart)
- [ ] Has run `npm run build-index`
- [ ] Has been manually tested by running in Spin/Bartholomew (hint: use `PREVIEW_MODE=1` and run `npm run styles` to update styling)
- [x] Headings are using Title Case
- [x] Code blocks have the programming language set to properly highlight syntax and the proper copy directive
- [ ] Have tested with `npm run test` and resolved all errors

2023-01-31 19:48 UTC, itowlson requested changes
We should rework the `up` section to distinguish trigger-specific flags from common ones.  At the moment we list the HTTP case, which I'm sure is most common, but users also run it with Redis apps or with no application at all.

2023-02-01 03:18 UTC, tpmccallum commented on content/cloud/cli-reference.md
> +        --tls-cert <TLS_CERT>
Thanks @itowlson 
This has been updated now.

2023-02-01 03:18 UTC, tpmccallum commented on content/cloud/cli-reference.md
> +        --listen <ADDRESS>
Thanks @itowlson 
This has been updated now.

2023-02-01 03:25 UTC, itowlson commented on content/cloud/cli-reference.md
> +Applications without triggers will accept any of the following options. The trigger-specific options are over and above what is shown directly below. Please see the next section for additional trigge
Sorry, I explained this badly.  There are no applications without triggers, and `spin up` won't accept _any_ options without an application.  (But we have to do _something_ when a user types `spin up --help` without an application, which is where the confusion arises.)  It's more like "The following options are always available", _plus_ any trigger-specific options if an application is present.

2023-02-01 04:37 UTC, itowlson approved these changes

2023-02-01 04:43 UTC, merged