Update documentation for distributing Spin apps
fermyon/developer pull request #302
Opened 2023-02-08 16:14 UTC by radu-matei

Signed-off-by: Radu Matei <radu.matei@fermyon.com>

2023-02-08 18:06 UTC, karthik2804 requested changes
I am not sure if these commands are intended to be copied, if not we need to prefix the code blocks with an annotation

```
<!-- @nocpy -->
```

2023-02-08 18:06 UTC, karthik2804 commented on content/spin/distributing-apps.md
> +```
```suggestion
```bash
```

2023-02-08 18:06 UTC, karthik2804 commented on content/spin/distributing-apps.md
> +```
```suggestion
```bash
```

2023-02-08 18:06 UTC, karthik2804 commented on content/spin/distributing-apps.md
> +```
```suggestion
```bash
```

2023-02-09 11:46 UTC, tpmccallum approved these changes
One can assume that the code blocks here are specific to radu's local env (i.e. the `ghcr.io/radu-matei` parts) and therefore it is safe to use the `<!-- @nocpy -->` to preface each of the code blocks. I think the reader will have enough information to understand what is going on and the subsequently perform the task without needing to copy and paste the code verbatim.

2023-02-09 11:46 UTC, tpmccallum commented on content/spin/distributing-apps.md
> +
```suggestion

<!-- @nocpy -->

```

2023-02-09 11:46 UTC, tpmccallum commented on content/spin/distributing-apps.md
> +
```suggestion

<!-- @nocpy -->

```

2023-02-09 11:46 UTC, tpmccallum commented on content/spin/distributing-apps.md
> +
```suggestion

<!-- @nocpy -->

```

2023-02-09 11:46 UTC, tpmccallum commented on content/spin/distributing-apps.md
```suggestion

<!-- @nocpy -->

```

2023-02-09 11:56 UTC, merged