Create 2023-the-wasm-meetup-berlin.md
fermyon/developer pull request #757
Opened 2023-07-24 19:15 UTC by karenhchu

Content must go through a pre-merge checklist.

## Pre-Merge Content Checklist

This documentation has been checked to ensure that:

- [ ] The `title, `template`, and `date` are all set
- [ ] Does this PR have a new menu item (anywhere in `templates/*.hbs` files) that points to a document `.md` that is set to publish in the future? If so please only publish the `.md` and `.hbs` changes in real-time (otherwise there will be a menu item pointing to a `.md` file that does not exist)
- [ ] File does not use CRLF, but uses plain LF (hint: use `cat -ve <filename> | grep '^M' | wc -l` and expect 0 as a result) 
- [ ] Has passed [`bart check`](https://developer.fermyon.com/bartholomew/quickstart)
- [ ] Has been manually tested by running in Spin/Bartholomew (hint: use `PREVIEW_MODE=1` and run `npm run styles` to update styling)
- [ ] Headings are using Title Case
- [ ] Code blocks have the programming language set to properly highlight syntax and the proper copy directive
- [ ] Have tested with `npm run test` and resolved all errors
- [ ] Relates to an existing (potentially outdated) blog article? If so please add URL in blog to point to this content.

2023-07-24 19:28 UTC, karthik2804 requested changes

2023-07-24 19:28 UTC, karthik2804 commented on content/events/2023-the-wasm-meetup-berlin.md
> +---
```suggestion
---

```

2023-07-24 19:47 UTC, karthik2804 requested changes

2023-07-24 19:47 UTC, karthik2804 commented on content/events/2023-the-wasm-meetup-berlin.md
> +description = "[The WebAssembly (Wasm) Meetup - Berlin](https://www.meetup.com/the-webassembly-wasm-meetup-berlin/) and [Kubernetes and Cloud Native Berlin](https://www.meetup.com/berlin-kubernetes-m
```suggestion
description = "[The WebAssembly (Wasm) Meetup - Berlin](https://www.meetup.com/the-webassembly-wasm-meetup-berlin/) and [Kubernetes and Cloud Native Berlin](https://www.meetup.com/berlin-kubernetes-meetup/) meet-up groups are co-organizing a July meet-up on July 26 at co.up in Berlin! Join Fermyon for a session on \"Bring[ing] your own Kubernetes and run Serverless WebAssembly\" starting at 6 PM."
```

2023-07-24 19:48 UTC, karthik2804 commented
My apologies for not catching that in the earlier review.

2023-07-24 21:53 UTC, karthik2804 approved these changes

2023-07-25 02:35 UTC, tpmccallum approved these changes

2023-07-25 02:35 UTC, tpmccallum commented on content/events/2023-the-wasm-meetup-berlin.md
> +description = "The WebAssembly (Wasm) Meetup - Berlin and Kubernetes and Cloud Native Berlin meet-up groups are co-organizing a July meet-up on July 26 at co.up in Berlin! Join Fermyon for a session
```suggestion
description = "The WebAssembly (Wasm) Meetup - Berlin and Kubernetes and Cloud Native Berlin meet-up groups are co-organizing a July meet-up on July 26 at the \"co.up community space\" in Berlin! Join Fermyon for a session on \"Bring[ing] your own Kubernetes and run Serverless WebAssembly\" starting at 6 PM."
```

2023-07-25 02:36 UTC, merged