Update build command output to not include RUST_LOG
fermyon/developer pull request #896
Opened 2023-09-19 11:16 UTC by tpmccallum

Signed-off-by: tpmccallum tim.mccallum@fermyon.com

2023-09-19 11:21 UTC, tpmccallum commented
Fixes https://github.com/fermyon/developer/issues/893

2023-09-19 19:19 UTC, itowlson requested changes
The tiniest thing I'm afraid, just need to revert one change.

2023-09-19 19:19 UTC, itowlson commented on content/spin/build.md
> +> Different components may be built from different languages, and so each component can have its own build command.  In addition, some components may be precompiled into Wasm modules, and don't need
The full stop was correct here. This is a side note; it does not lead into the subsequent tab block.
```suggestion
> Different components may be built from different languages, and so each component can have its own build command.  In addition, some components may be precompiled into Wasm modules, and don't need a build command at all.  If a component doesn't have a build command, `spin build` just skips it.
```

2023-09-20 03:57 UTC, itowlson approved these changes

2023-09-20 03:59 UTC, merged