add llm remote_http option
fermyon/developer pull request #913
Opened 2023-10-02 16:24 UTC by karthik2804

2023-10-02 19:15 UTC, itowlson requested changes
Looks good - just a few suggestions / omissions.  I agree you definitely need to mention / link the `cloud-gpu` plugin, otherwise it's all a bit theoretical!  I'm a bit torn between your current neutral approach (which is correct) versus leading off with cloud-gpu and including instructions (which is opinionated but in practice it's what this means today, and is more likely to jump out as an actual solution).  Although there are better places to do that - this page is pretty out-of-the-way!  What you have is fine, I am just thinking out loud.

I wonder if you want to add anything to the LLM tutorials or API guide drawing readers' attention to cloud-gpu?

2023-10-02 19:30 UTC, radu-matei commented on content/spin/dynamic-configuration.md
> +Spin provides an Large Language Model interface for interacting with LLMs for inferencing and embedding. The default host implementation is to use local CPU/GPU compute.  However, the Spin runtime co
"Spin provides *a* Large Language Model interface"

2023-10-03 03:51 UTC, itowlson approved these changes
I have suggested some alternative wording for the LLM proxy paragraph but it's not a blocker

2023-10-03 03:51 UTC, itowlson commented on content/spin/dynamic-configuration.md
> +Currently, using this runtime config to use remote compute requires an user to deploy their own LLM proxy service. A reference implementation for it can be found in the [`spin-cloud-gpu plugin reposi
wording got a bit intricate for this bear of very little brain
```suggestion
Currently, the remote compute option requires an user to deploy their own LLM proxy service. Fermyon Cloud users can do this using the [`cloud-gpu` plugin](https://github.com/fermyon/spin-cloud-gpu).  If you prefer to create and deploy your own proxy service, you can find a reference implementation of the proxy protocol in the [`spin-cloud-gpu plugin repository`](https://github.com/fermyon/spin-cloud-gpu/blob/main/fermyon-cloud-gpu/src/index.ts). 
```

2023-10-03 03:52 UTC, merged