Change NoOps to SQLite (in spin/v2 and cloud folders only)
fermyon/developer pull request #959
Opened 2023-10-25 22:51 UTC by tpmccallum

Content must go through a pre-merge checklist.

## Pre-Merge Content Checklist

This documentation has been checked to ensure that:

- [ ] The `title, `template`, and `date` are all set
- [ ] Does this PR have a new menu item (anywhere in `templates/*.hbs` files) that points to a document `.md` that is set to publish in the future? If so please only publish the `.md` and `.hbs` changes in real-time (otherwise there will be a menu item pointing to a `.md` file that does not exist)
- [ ] File does not use CRLF, but uses plain LF (hint: use `cat -ve <filename> | grep '^M' | wc -l` and expect 0 as a result) 
- [ ] Has passed [`bart check`](https://developer.fermyon.com/bartholomew/quickstart)
- [ ] Has been manually tested by running in Spin/Bartholomew (hint: use `PREVIEW_MODE=1` and run `npm run styles` to update styling)
- [ ] Headings are using Title Case
- [ ] Code blocks have the programming language set to properly highlight syntax and the proper copy directive
- [ ] Have tested with `npm run test` and resolved all errors
- [ ] Relates to an existing (potentially outdated) blog article? If so please add URL in blog to point to this content.

2023-10-25 23:01 UTC, macolso reviewed
Looks great, thank you @tpmccallum! I added a suggestion to add a brief callout to help user through the name transition.

2023-10-25 23:01 UTC, macolso commented on content/cloud/changelog/cloud-noops-sql-db.md
> +Spin developers can now persist relational data generated by their Spin application in a database that is provisioned and managed entirely by Fermyon Cloud on their behalf. No need to worry about dat
Can we add a callout to help handhold users through the transition?

```suggestion
Spin developers can now persist relational data generated by their Spin application in a database that is provisioned and managed entirely by Fermyon Cloud on their behalf. No need to worry about database operations, connection strings, or resource management with Fermyon Cloud's SQLite Database; we've got you covered.

>> Note: Fermyon Cloud NoOps SQL Database has been renamed to Fermyon Cloud SQLite Database. Your workload is not impacted by this name change, and no actions are required on your end. 
```

2023-10-25 23:05 UTC, itowlson commented
Wait what's this. are we meant to be changing this in the cloud plugin and stuff as well?

2023-10-25 23:06 UTC, technosophos approved these changes
Approve, with @macolso 's suggested addition

2023-10-26 00:37 UTC, itowlson requested changes
I'm afraid it's gone a bit awry on the Spin side.  We should not capitalise "database" except in the marketing context; e.g. when we mention that local KV is backed by a SQLite database, that's _not_ a Fermyon Cloud Capitalised Database, it's just a normal improper noun.

Other than those, looks good - thanks!

2023-10-26 00:37 UTC, itowlson commented on content/cloud/faq.md
> +| SQLite Database count | 1 | 1 |  Contact us
I don't think this is the brand name, just "database" in its "the concept that Fermyon Cloud SQLite Database implements" which is why it wasn't NoOps before

```suggestion
| SQLite database count | 1 | 1 |  Contact us
```

2023-10-26 00:37 UTC, itowlson commented on content/cloud/faq.md
> +| SQLite Database size (GB) | 1 | 2 | Contact us
```suggestion
| SQLite database size (GB) | 1 | 2 | Contact us
```

2023-10-26 00:37 UTC, itowlson commented on content/cloud/linking-applications-to-resources-using-labels.md
> +Many Spin applications require data storage between invocations. Fermyon Cloud offers two methods for this: key-value storage and SQLite Databases. However, the relationship between applications and
again, this was not previously captialised - next to "key-value storage" it looks weird to me but I don't know what the official branding guidelines say _grin_

2023-10-26 00:37 UTC, itowlson commented on content/cloud/noops-sql-db.md
> +* For support or feature feedback, please join our [Discord channel #no-ops-db-beta](https://discord.gg/XxkZvsya). This is the place where you can provide feedback and request assistance from the Fer
How do you feel about all the extra words here?  To me "all things SQLite Database" feels more concise than "all matters related to using SQLite Databases in Spin and Fermyon Cloud."  Is the idea that non-English speakers might find the former too idiomatic?

2023-10-26 00:37 UTC, itowlson commented on content/spin/dynamic-configuration.md
> +Spin provides built-in key-value storage. This storage is backed by an SQLite Database embedded in Spin by default. However, the Spin runtime configuration file (runtime-config.toml) can be updated t
This is definitely _not_ the Cloud brand name, it's just an ordinary non-proper-named SQLite database on your local disk.

```suggestion
Spin provides built-in key-value storage. This storage is backed by an SQLite database embedded in Spin by default. However, the Spin runtime configuration file (runtime-config.toml) can be updated to not only modify the SQLite configuration but also choose to use a different backing store. The available store options are the embedded SQLite database, an external Redis database or Azure CosmosDB.
```

2023-10-26 00:37 UTC, itowlson commented on content/spin/dynamic-configuration.md
> +Spin provides built-in SQLite storage. By default, this is backed by a database that Spin creates for you underneath your application directory (in the `.spin` subdirectory). However, you can use the
Same
```suggestion
Spin provides built-in SQLite storage. By default, this is backed by a database that Spin creates for you underneath your application directory (in the `.spin` subdirectory). However, you can use the Spin runtime configuration file (`runtime-config.toml`) to add and customize SQLite databases.
```

2023-10-26 00:37 UTC, itowlson commented on content/spin/dynamic-configuration.md
> +The following example `runtime-config.toml` tells Spin to map the `default` database to an SQLite Database elsewhere in the file system:
```suggestion
The following example `runtime-config.toml` tells Spin to map the `default` database to an SQLite database elsewhere in the file system:
```

2023-10-26 00:37 UTC, itowlson commented on content/spin/rdbms-storage.md
> +* A built-in [SQLite Database](./sqlite-api-guide), which is always available and requires no management on your part.
```suggestion
* A built-in [SQLite database](./sqlite-api-guide), which is always available and requires no management on your part.
```

2023-10-26 00:37 UTC, itowlson commented on content/spin/see-what-people-have-built-with-spin.md
> +Check out our [NoOps and Serverless Are the Perfect Pair](https://www.fermyon.com/blog/noops-and-serverless-are-the-perfect-pair) blog article that provides a SQLite Storage example (using Javascript
```suggestion
Check out our [NoOps and Serverless Are the Perfect Pair](https://www.fermyon.com/blog/noops-and-serverless-are-the-perfect-pair) blog article that provides a SQLite Database example (using JavaScript).
```

2023-10-26 00:37 UTC, itowlson commented on content/spin/sqlite-api-guide.md
> +Spin provides an interface for you to persist data in an SQLite Database managed by Spin. This database allows Spin developers to persist relational data across application invocations.
```suggestion
Spin provides an interface for you to persist data in an SQLite database managed by Spin. This database allows Spin developers to persist relational data across application invocations.
```

2023-10-26 00:37 UTC, itowlson commented on content/spin/sqlite-api-guide.md
> +{{ details "Why do I need a Spin interface? Why can't I just use my own external database?" "You can absolutely still use your own external database either with the [MySQL or Postgres APIs](./rdbms-s
```suggestion
{{ details "Why do I need a Spin interface? Why can't I just use my own external database?" "You can absolutely still use your own external database either with the [MySQL or Postgres APIs](./rdbms-storage). However, if you're interested in quick, local relational storage without any infrastructure set-up then Spin's SQLite database is a great option." }}
```

2023-10-26 00:37 UTC, itowlson commented on content/spin/sqlite-api-guide.md
> +By default, a given component of an app will not have access to any SQLite Databases. Access must be granted specifically to each component via the component manifest.  For example, a component could
```suggestion
By default, a given component of an app will not have access to any SQLite databases. Access must be granted specifically to each component via the component manifest.  For example, a component could be given access to the default store using:
```

2023-10-26 00:37 UTC, itowlson commented on content/spin/sqlite-api-guide.md
> +The Spin SDK surfaces the Spin SQLite Database interface to your language.
```suggestion
The Spin SDK surfaces the Spin SQLite database interface to your language.
```

2023-10-26 00:37 UTC, itowlson commented on content/spin/sqlite-api-guide.md
> +As mentioned above, by default, a given component of an app will not have access to any SQLite Databases. Access must be granted specifically to each component via the component manifest, using the `
```suggestion
As mentioned above, by default, a given component of an app will not have access to any SQLite databases. Access must be granted specifically to each component via the component manifest, using the `component.sqlite_databases` field in the manifest.
```

2023-10-26 00:37 UTC, itowlson commented on content/spin/v2/dynamic-configuration.md
> +Spin provides built-in key-value storage. This storage is backed by an SQLite Database embedded in Spin by default. However, the Spin runtime configuration file (runtime-config.toml) can be updated t
I'm guessing the same ones as in the previous Spin docs are also going to be in the `v2` directory - take this comment as standing in repeating all the suggestions on the v1 docs _grin_

```suggestion
Spin provides built-in key-value storage. This storage is backed by an SQLite database embedded in Spin by default. However, the Spin runtime configuration file (runtime-config.toml) can be updated to not only modify the SQLite configuration but also choose to use a different backing store. The available store options are the embedded SQLite database, an external Redis database or Azure CosmosDB.
```

2023-10-26 00:49 UTC, tpmccallum reviewed
Couple of capitalization updates.

2023-10-26 00:49 UTC, tpmccallum commented on content/cloud/linking-applications-to-resources-using-labels.md
> +Many Spin applications require data storage between invocations. Fermyon Cloud offers two methods for this: key-value storage and SQLite Databases. However, the relationship between applications and
```suggestion
Many Spin applications require data storage between invocations. Fermyon Cloud offers two methods for this: key-value storage and SQLite databases. However, the relationship between applications and databases isn't strictly one-to-one. A single database might be used by multiple applications, while an application could utilize several databases. There might even be a need to maintain a database that isn't utilized by any applications, perhaps for analytics or compliance reasons. All of these scenarios can occur as applications are independently deployed, upgraded, and retired, without any particular application needing to be aware of how others might be using the same databases.
```

2023-10-26 00:49 UTC, tpmccallum commented on content/cloud/noops-sql-db.md
> +* For support or feature feedback, please join our [Discord channel #no-ops-db-beta](https://discord.gg/XxkZvsya). This is the place where you can provide feedback and request assistance from the Fer
```suggestion
* For support or feature feedback, please join our [Discord channel #no-ops-db-beta](https://discord.gg/XxkZvsya). This is the place where you can provide feedback and request assistance from the Fermyon Cloud team regarding all things SQLite Database.
```

2023-10-26 00:51 UTC, tpmccallum reviewed
Respond to review.

2023-10-26 00:51 UTC, tpmccallum commented on content/spin/see-what-people-have-built-with-spin.md
> +Check out our [NoOps and Serverless Are the Perfect Pair](https://www.fermyon.com/blog/noops-and-serverless-are-the-perfect-pair) blog article that provides a SQLite Storage example (using Javascript
```suggestion
Check out our [NoOps and Serverless Are the Perfect Pair](https://www.fermyon.com/blog/noops-and-serverless-are-the-perfect-pair) blog article that provides an SQLite Database example (using JavaScript).
```

2023-10-26 00:58 UTC, tpmccallum reviewed
Review

2023-10-26 00:58 UTC, tpmccallum commented on content/spin/see-what-people-have-built-with-spin.md
> +Check out our [NoOps and Serverless Are the Perfect Pair](https://www.fermyon.com/blog/noops-and-serverless-are-the-perfect-pair) blog article that provides a SQLite Storage example (using Javascript
This is outdated it seems.

2023-10-26 00:58 UTC, tpmccallum commented on content/spin/see-what-people-have-built-with-spin.md
> +Check out our [NoOps and Serverless Are the Perfect Pair](https://www.fermyon.com/blog/noops-and-serverless-are-the-perfect-pair) blog article that provides a SQLite Storage example (using Javascript
```suggestion
Check out our [NoOps and Serverless Are the Perfect Pair](https://www.fermyon.com/blog/noops-and-serverless-are-the-perfect-pair) blog article that provides an SQLite Database example (using JavaScript).
```

2023-10-26 01:07 UTC, tpmccallum reviewed
Trying to resolve outdated suggestion issue

2023-10-26 01:07 UTC, tpmccallum commented on content/spin/see-what-people-have-built-with-spin.md
> +Check out our [NoOps and Serverless Are the Perfect Pair](https://www.fermyon.com/blog/noops-and-serverless-are-the-perfect-pair) blog article that provides an SQLite Storage example (using Javascrip
```suggestion
Check out our [NoOps and Serverless Are the Perfect Pair](https://www.fermyon.com/blog/noops-and-serverless-are-the-perfect-pair) blog article that provides an SQLite database example (using Javascript).
```

2023-10-26 01:07 UTC, tpmccallum commented on content/spin/v2/see-what-people-have-built-with-spin.md
> +Check out our [NoOps and Serverless Are the Perfect Pair](https://www.fermyon.com/blog/noops-and-serverless-are-the-perfect-pair) blog article that provides an SQLiteite Storage example (using Javasc
```suggestion
Check out our [NoOps and Serverless Are the Perfect Pair](https://www.fermyon.com/blog/noops-and-serverless-are-the-perfect-pair) blog article that provides an SQLite database example (using Javascript).
```

2023-10-26 01:09 UTC, tpmccallum reviewed
Typo

2023-10-26 01:13 UTC, tpmccallum commented
Thank @itowlson 
Happy with this one if you are; thanks for the extra suggestions.

2023-10-26 01:16 UTC, itowlson approved these changes

2023-10-26 01:35 UTC, tpmccallum reviewed
Only change written text (not terminal output)

2023-10-26 01:35 UTC, tpmccallum commented on content/spin/cli-reference.md
> +            Run an SQLite statement such as a migration against the default database. To run from a
```suggestion
            Run a SQLite statement such as a migration against the default database. To run from a
```

2023-10-26 01:35 UTC, tpmccallum commented on content/spin/cli-reference.md
> +            Run an SQLite statement such as a migration against the default database. To run from a
```suggestion
            Run a SQLite statement such as a migration against the default database. To run from a
```

2023-10-26 01:44 UTC, itowlson approved these changes

2023-10-26 01:45 UTC, merged